option(LIMEN_BUILD_OPENGL "Build limen_opengl.hdll." ON)
option(LIMEN_BUILD_VULKAN "Build limen_vulkan.hdll." ON)
option(LIMEN_BUILD_SHADERC "Build shaderc support into limen_vulkan.hdll." ON)
option(LIMEN_BUILD_D3D11 "Build limen_d3d11.hdll." ${WIN32})
option(LIMEN_BUILD_D3D12 "Build limen_d3d12.hdll." ${WIN32})
option(LIMEN_BUILD_DLSS "Build limen_dlss.hdll for the D3D12 backend." ${WIN32})
option(LIMEN_BUILD_AFTERMATH "Build NVIDIA Nsight Aftermath support into limen_d3d12.hdll." OFF)
option(LIMEN_BUILD_TESTS "Build Lumen tests." OFF)

set(LIMEN_SDL3_SOURCE_DIR "" CACHE PATH "Optional SDL3 source tree; otherwise SDL3 is fetched by CMake.")
set(LIMEN_HASHLINK_ROOT "" CACHE PATH "Path to a HashLink source checkout.")
set(LIMEN_HASHLINK_LIBRARY "" CACHE FILEPATH "Path to the HashLink library for standalone builds.")
set(LIMEN_DXCOMPILER_LIBRARY "" CACHE FILEPATH "Path to the DirectX Shader Compiler import library.")
set(LIMEN_DXCOMPILER_RUNTIME_DLL "" CACHE FILEPATH "Path to dxcompiler.dll to package beside the Lumen modules.")
set(LIMEN_DXIL_RUNTIME_DLL "" CACHE FILEPATH "Path to dxil.dll to package beside the Lumen modules.")
set(LIMEN_STREAMLINE_SDK_ROOT "" CACHE PATH "Path to the NVIDIA Streamline SDK.")
set(LIMEN_STREAMLINE_INTERPOSER_LIBRARY "" CACHE FILEPATH "Path to the NVIDIA Streamline import library.")
set(LIMEN_AFTERMATH_SDK_ROOT "" CACHE PATH "Path to the NVIDIA Nsight Aftermath SDK.")
set(LIMEN_AFTERMATH_LIBRARY "" CACHE FILEPATH "Path to the NVIDIA Nsight Aftermath import library.")
set(LIMEN_AFTERMATH_RUNTIME_DLL "" CACHE FILEPATH "Path to the NVIDIA Nsight Aftermath runtime DLL.")
